suricata_report:
  description: >
    Examine the provided suricata alerts, and provide a security analysis of the alert content. 
    Consider how the traffic may fit within a wider context and the intentions any threat actor. 
    Use the classifier_tool to pass the event data, pass the data as plain text. The tool will run a classificiation ML algorithm to help determine if it is malicious. It was trained on labelled IOT-23 attacks. 
    It will return a classification of maliciousness from 0-1, with 1 being malicious. 
    Label the traffic high, medium or low concern, and provide a recommendation if it warrants further investigation or containment. The alerts are provided here:
    event={event}
  expected_output: >
    A comprehensive report on the alerts.
  agent: suricata_analyst
  markdown: true 
  output_file: output/suricata_report.md

incident_planning:
  description: >
    Plan a response to the incident based on the analysis provided by the suricata_analyst. Your response should be focused to immediate threat areas, containment and elimination of potential attack vectors in order to restore normal operation. The preservation of evidence should be considered as well. Consider the device, upstream routers and switches, the (sub)network(s) and users on the network.
  expected_output: >
    A report for dissemination to incident responders, covering all required points in clear and delineated sections so that responders may access wider context but easily understand their own tasks. 
  agent: incident_manager 
  output_file: output/incident_plan.md
  context: ["suricata_report"]

email_task:
  description: >
    The Suricata Analyst and Incident Planner have created reports on the network activity and any planned responses, please paraphrase this for the non-technical site manager and provide him an update in his email.
  expected_output: >
    An email describing the network incident threat and planned responses, if any. Please also provide a file artifact of the email. 
  agent: email_agent
  output_file: output/email.txt
  context: ["suricata_report", "incident_planning"] 
