suricata_report:
  description: >
    Examine the provided suricata alerts from a VLAN of IoT devices, and 
    provide a security analysis of the alert content. Consider how the traffic may 
    fit within a wider context and the intentions any threat actor. Use the classifier_tool 
    to parse the event data, pass the data as plain text. The tool will run a 
    classification ML algorithm to help determine if it is malicious. It was 
    trained on labelled IOT-23 attacks. It will return a classification of 
    maliciousness from 0-1, with 1 being malicious. Analyse the traffic using 
    the classifier and the raw data both. Label the traffic high, medium or low 
    concern, and provide a recommendation if it warrants further investigation 
    or containment, if not then note it as normal traffic behaviour. 
    Send all the data at the same time. The alerts are provided here: {event}
  expected_output: >
    A comprehensive report on the alerts formatted in markdown in which:
    Each malicious or potentially malicious alert is analysed in detail,
    The source and destination of the traffic is identified,
    metadata about the traffic is provided (eg. protocol, ports, packet sizes, signature IDs),
    The timestamps of the traffic are noted,
    A clear classification of the traffic is given (high, medium, low concern),
  agent: suricata_analyst
  markdown: true 
  output_file: output/suricata_report.md

incident_planning:
  description: >
    Plan a response to the incident on the IoT device VLAN based on the 
    analysis provided by the suricata_analyst. Your response should be focused 
    to immediate threat areas, containment and elimination of potential attack 
    vectors in order to restore normal operation. The preservation of evidence 
    should be considered as well. Consider the device, upstream routers and 
    switches, the (sub)network(s) and users on the network. If traffic is
    normal, then note this and tell responders to continue monitoring as normal.
  expected_output: >
    A report for dissemination to incident responders, being simple
    and informative; formatted in markdown. It can only include information 
    under these headings:
    - The result of the classifier_tool rating for each packet is included (if available),
    - Summary of the incident
    - Immediate action that have been taken
    - Further actions to be taken
    - Preservation of evidence
    - Communication plan
  agent: incident_manager 
  output_file: output/incident_plan.md
  context: ["suricata_report"]

email_task:
  description: >
    The Suricata Analyst and Incident Planner have created reports on the 
    network activity from the IoT device vlan, and any planned responses. 
    Please paraphrase this for the non-technical site manager and provide 
    an update as an email. As the incident is still in progress, make 
    sure to phrase this in the present tense.
  expected_output: >
    An email describing the network incident threat and planned responses, if 
    any. This email must be beneficial and reassuring for stakeholders whilst 
    also informing. Include:
    - Address the email to 'Site Manager'
    - Time of threat
    - Actions that have been taken
    - What as (we) the system is doing to further resolve the issue
    - Sign the email as 'IDS 3000 Automated System'
    This information can be extrapolaed from the suricata_report and 
    incident_planning reports. The email should be concise and to the point.
    Please also provide a file artifact of the email.
  agent: email_agent
  output_file: output/email.txt
  context: ["suricata_report", "incident_planning"] 

cisco_configuration_report:
  description: >
    Analyse an Incident report from the Incident Manager based on a suspected
    network incident on the IoT device VLAN, and briefly analyse the Suricata
    Analyst's report for context. Decide, based on the instructions of the 
    Incident manager the recommended configuration changes to the Cisco router
    'main-router' and switch 'switch1', and provide these configurations in a
    report. You should create a markdown report giving your very brief analysis
    and recommended changes, then provide the code blocks as separate blocks.
    Do not include the incident plan or suricata analysis in your report. 
    If traffic is routine then you should make no changes to the configuration,
    only providing `!comments` for each config and note this in your report.
  expected_output: >
    A markdown report detailing what actions are being taken (if any) and two 
    code blocks, one for Cisco router commands, one for Cisco switch commands.
    These commands must focus on:
    - Blocking malicious IP addresses
    - Blocking malicious ports
    - Isolating affected devices
    - Containment of lateral movement
    - Any other configuration changes that would help mitigate the threat
    - If absolutely nescessary, enable logging for further investigation however,
    keep in mind that suricata is already running on the network.
  agent: cisco_admin
  output_file: output/cisco_configuration_report.md
  context: ["suricata_report", "incident_planning"]

supply_router_commands:
  description: >
    Provide any router commands created by the cisco_configuration report in a
    plain text file with no context or comments. These will be pasted directly
    into a Cisco console.
  expected_output: A list of router commands in plain text.
  agent: cisco_admin
  output_file: output/cisco_router_commands.txt
  context: ["cisco_configuration_report"]

supply_switch_commands:
  description: >
    Provide any switch commands created by the cisco_configuration report in a
    plain text file with no context or comments. These will be pasted directly
    into a Cisco console.
  expected_output: A list of switch commands in plain text.
  agent: cisco_admin
  output_file: output/cisco_switch_commands.txt
  context: ["cisco_configuration_report"]
