#tasks.yaml

observe_task: 
  description: >
    Watch and listen for events returned from the observe tool. Once an event or multiple events have been communicated pass them to the analysis_task for further action.
  expected_output: >
    events as they are provided from the tool are to be passed to the analysis_task
  agent: observer_agent

analysis_task:
  description: >
    Conduct an analysis of the provided alerts from observe_task, categorising the alerts based
    on their risk potential as 'high risk,' 'medium risk', 'low risk', or
    benign. 
  expected_output: >
    A full report explaining the nature of the alerts, the nature of the threat
    (if any), the devices that may be causing the alerts and the human readable
    overview of the alerts. Format the report as markdown.
  agent: suricata_analyst
  output_file: analysis.md

email_task:
  description: >
    Send the report as plain text using the send_email tool
  expected_output: >
    The report from analysis_task in plain text sent to send_email tool. Not in JSON just plain text.
  agent: email_agent

#
# research_task:
#   description: >
#     Conduct a thorough research about {topic}
#     Make sure you find any interesting and relevant information given
#     the current year is {current_year}.
#   expected_output: >
#     A list with 10 bullet points of the most relevant information about {topic}
#   agent: researcher
# 
# reporting_task:
#   description: >
#     Review the context you got and expand each topic into a full section for a report.
#     Make sure the report is detailed and contains any and all relevant information.
#   expected_output: >
#     A fully fledged report with the main topics, each with a full section of information.
#     Formatted as markdown without '```'
#   agent: reporting_analyst
